# Generated by Django 5.0.2 on 2024-06-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadUser',
            fields=[
                ('id_ReadUser', models.AutoField(db_column='idReadUser', primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Read User',
                'verbose_name_plural': 'read Users',
                'db_table': 'Read Users',
            },
        ),
        migrations.CreateModel(
            name='WriteUser',
            fields=[
                ('id_WriteUser', models.AutoField(db_column='idWriteUser', primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('empresa', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Write User',
                'verbose_name_plural': 'Write users',
                'db_table': 'Write Users',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id_Newspaper', models.AutoField(db_column='idNewspaper', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_noticia', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=999999)),
                ('user_fk', models.ForeignKey(db_column='idWriteUser', on_delete=django.db.models.deletion.CASCADE, to='RegisterAndLogin.writeuser')),
            ],
            options={
                'verbose_name': 'Newspaper',
                'verbose_name_plural': 'Newspapers',
                'db_table': 'Newspapers',
            },
        ),
    ]
