# Generated by Django 5.0.2 on 2024-07-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAndLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readuser',
            name='password',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='writeuser',
            name='password',
            field=models.CharField(max_length=100000),
        ),
    ]
