# Generated by Django 5.0.2 on 2024-07-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAndLogin', '0002_alter_readuser_password_alter_writeuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readuser',
            name='password',
            field=models.CharField(max_length=999999),
        ),
        migrations.AlterField(
            model_name='writeuser',
            name='password',
            field=models.CharField(max_length=999999),
        ),
    ]
