# Generated by Django 5.0.2 on 2024-07-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAndLogin', '0003_alter_readuser_password_alter_writeuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='writeuser',
            name='password',
        ),
    ]
