# Generated by Django 5.0.6 on 2024-07-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caosnoticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='ContactoFormModel',
        ),
    ]
