<<<<<<< HEAD
# Generated by Django 4.1.2 on 2024-07-07 22:46
=======
# Generated by Django 5.0.2 on 2024-07-09 08:55
>>>>>>> 883add300c7b5dd879efc4f48bb5a6d8fed3f527

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnoticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
