# Generated by Django 5.0.6 on 2024-07-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caosnoticias', '0002_rename_mensaje_contactoformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactoFormModel',
        ),
    ]
