# Generated by Django 5.0.2 on 2024-07-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caosnoticias', '0003_merge_20240709_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
