# Generated by Django 5.0.6 on 2024-07-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_noticias', '0002_rename_fecha_creacion_noticia_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
