# Generated by Django 5.0.6 on 2024-07-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_noticias', '0003_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
