# Generated by Django 5.0.6 on 2024-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_noticias', '0004_noticia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('----', '---'), ('policial', 'Policial'), ('economia', 'Economía'), ('deportes', 'Deportes'), ('ciencia_tecnologia', 'Ciencia y Tecnología'), ('internacional', 'Internacional')], max_length=50),
        ),
    ]
